<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="骑手端测试结果"
           tests="6"
           failures="1"
           errors="0"
           skipped="3"
           time="3.635">
  <properties />
            <testcase name="queryHistroyOrder" time="0.389" classname="com.xiaoxin.gdata.data.test.qa.rider.redirSetPageTest">
                <failure type="java.lang.AssertionError"
                  message="expected [成功1] but found [成功]"
              >
<![CDATA[java.lang.AssertionError: expected [成功1] but found [成功]
  org.testng.Assert.fail(Assert.java:97)
  org.testng.Assert.assertEqualsImpl(Assert.java:136)
  org.testng.Assert.assertEquals(Assert.java:118)
  org.testng.Assert.assertEquals(Assert.java:575)
  org.testng.Assert.assertEquals(Assert.java:585)
  com.xiaoxin.gdata.data.test.qa.rider.redirSetPageTest.queryHistroyOrder(redirSetPageTest.java:14)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
  org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
  org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:204)
  org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
  org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
  org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
  java.util.ArrayList.forEach(ArrayList.java:1257)
  org.testng.TestRunner.privateRun(TestRunner.java:770)
  org.testng.TestRunner.run(TestRunner.java:591)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
  org.testng.SuiteRunner.access$000(SuiteRunner.java:41)
  org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:443)
  org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:67)
  java.util.concurrent.FutureTask.run(FutureTask.java:266)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  java.lang.Thread.run(Thread.java:748)
]]>
      </failure>

          </testcase>
  
            <testcase name="queryHistroyOrder" time="0.0" classname="com.xiaoxin.gdata.data.test.qa.rider.redirSetPageTest">
          <skipped />
    </testcase>
            <testcase name="queryHistroyOrder" time="0.0" classname="com.xiaoxin.gdata.data.test.qa.rider.redirSetPageTest">
          <skipped />
    </testcase>
            <testcase name="queryHistroyOrder" time="0.0" classname="com.xiaoxin.gdata.data.test.qa.rider.redirSetPageTest">
          <skipped />
    </testcase>
  
            <testcase name="getBills" time="1.538" classname="com.xiaoxin.gdata.data.test.qa.rider.redirSetPageTest" />
                <testcase name="getSch" time="0.401" classname="com.xiaoxin.gdata.data.test.qa.rider.redirSetPageTest" />
      
</testsuite>
